# Generated by Django 5.2.1 on 2025-05-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='auteur',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='contenu',
        ),
        migrations.RemoveField(
            model_name='article',
            name='date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='titre',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
